### ISSUE TITLE
Put fade abilities back into weapon slots

### ISSUE THREAD

**Issue by Rusty01** [MysteriousMilk/NS2_CombatPlusPlus#38]
If we could have tier abilities accessible via, number keys that would be great. Has been a lot of requests for it.

**Comment by MysteriousMilk** [comment]
Are you saying compared to the original combat mod?

I haven't hooked up the alien abilities yet but when I do, it will work a little different than the original combat mod.  Instead of purchasing "tier 2" and "tier 3", you'll actually upgrade to stab, meta, and adv meta.  Upon purchasing those upgrades, the ones that should appear in weapons slots will and the ones that shouldn't will not.

It shouldn't be any different from vanilla ns2 in that aspect.  Only difference is the individual player purchases the ability instead of a commander researching it.

**Comment by Rusty01** [comment]
Basically recent in NS2 they removed the option to press "2" for
metabalize. you can only metabolize with the shift key.
NS2+ added a feature shortly after allowing you to use your keyboard "1",
"2", "3" weapon slots for fade again.
As NS2+ is't compatible and a lot of us fades really relied on that
function it would be great if you could add it back in.

**Comment by MysteriousMilk** [comment]
@Rusty01 The plan is to be compatible with NS2+.  I just haven't had the time to look into it yet as I'm still working on the core mechanics.

**Comment by MysteriousMilk** [comment]
NS2+ seems to be working with the mod thus far.  Closing this issue for now as NS2+ can reenable this feature.
